#!/usr/bin/env python3
"""Builds the Court Search app icon for both platforms from one description.

Scales of justice, paper white on oxblood (DESIGN.md's reporter voice). Every
part is a filled shape: strokes render inconsistently across rasterizers, and
Android's VectorDrawable wants explicit paths anyway.

Writes design/app-icon.svg, the iOS AppIcon set (needs ImageMagick's `magick`),
and the Android adaptive icon (foreground vector, background colour, and the
same foreground as the themed monochrome layer).
"""
import json, math, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
GROUND, MARK = "#7A1F2B", "#FBF8F3"


def bar(x1, y1, x2, y2, width):
    """A line as a filled quad with round ends approximated by end circles."""
    dx, dy = x2 - x1, y2 - y1
    length = math.hypot(dx, dy)
    nx, ny = -dy / length * width / 2, dx / length * width / 2
    quad = f"M {x1+nx:.1f} {y1+ny:.1f} L {x2+nx:.1f} {y2+ny:.1f} L {x2-nx:.1f} {y2-ny:.1f} L {x1-nx:.1f} {y1-ny:.1f} Z"
    return [quad, circle(x1, y1, width / 2), circle(x2, y2, width / 2)]


def circle(cx, cy, r):
    return (f"M {cx-r:.1f} {cy:.1f} A {r:.1f} {r:.1f} 0 1 0 {cx+r:.1f} {cy:.1f} "
            f"A {r:.1f} {r:.1f} 0 1 0 {cx-r:.1f} {cy:.1f} Z")


def pan(cx, y, half, depth):
    return f"M {cx-half} {y} L {cx+half} {y} A {half} {depth} 0 0 1 {cx-half} {y} Z"


PATHS = []
PATHS += bar(252, 348, 772, 348, 30)            # beam
PATHS += bar(512, 300, 512, 730, 30)            # pillar
for cx in (252, 772):                            # chains and pans
    PATHS += bar(cx, 348, cx - 86, 566, 20)
    PATHS += bar(cx, 348, cx + 86, 566, 20)
    PATHS.append(pan(cx, 566, 110, 78))
PATHS.append(circle(512, 292, 34))               # finial
PATHS += bar(392, 736, 632, 736, 40)             # base

svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" role="img" '
       f'aria-label="Court Search icon: scales of justice">',
       "  <!-- Generated by scripts/build-icons.py; edit the script, not this file. -->",
       f'  <rect width="1024" height="1024" fill="{GROUND}"/>']
svg += [f'  <path d="{d}" fill="{MARK}"/>' for d in PATHS]
svg.append("</svg>")
(ROOT / "design").mkdir(exist_ok=True)
master = ROOT / "design/app-icon.svg"
master.write_text("\n".join(svg) + "\n")

# iOS: one 1024 px opaque image; Xcode derives every size from it.
iconset = ROOT / "ios/CourtSearch/Assets.xcassets/AppIcon.appiconset"
iconset.mkdir(parents=True, exist_ok=True)
subprocess.run(["magick", "-background", "none", "-density", "300", str(master), "-resize", "1024x1024",
                "-alpha", "remove", "-alpha", "off", str(iconset / "AppIcon.png")], check=True)
(iconset / "Contents.json").write_text(json.dumps({
    "images": [{"filename": "AppIcon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}],
    "info": {"author": "xcode", "version": 1}}, indent=2) + "\n")
(iconset.parent / "Contents.json").write_text(json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")

# Android: adaptive icon. The 108dp canvas shows only its central 66-72dp, so the
# mark is scaled to sit inside that safe zone.
res = ROOT / "android/app/src/main/res"
scale = 62 / 760                                   # mark is ~760 units wide in the master
tx, ty = 54 - 512 * scale, 54 - 520 * scale
paths = "\n".join(f'        <path android:fillColor="{MARK}" android:pathData="{d}" />' for d in PATHS)
(res / "drawable").mkdir(parents=True, exist_ok=True)
(res / "drawable/ic_launcher_foreground.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/build-icons.py; edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    <group android:scaleX="{scale:.5f}" android:scaleY="{scale:.5f}" android:translateX="{tx:.3f}" android:translateY="{ty:.3f}">
{paths}
    </group>
</vector>
''')
(res / "values").mkdir(exist_ok=True)
(res / "values/ic_launcher_background.xml").write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">{GROUND}</color>
</resources>
''')
(res / "mipmap-anydpi-v26").mkdir(exist_ok=True)
adaptive = '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
'''
for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
    (res / "mipmap-anydpi-v26" / name).write_text(adaptive)
print("icons written")
